DailyDiary/Models/Diary.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DailyDiary.Models
{
	public class Diary
	{
        [Key]
        public int SrNo { get; set; }
        public string Diary_Content { get; set; }
        public DateTime Diary_Entry_Date { get; set; }
        public string Author { get; set; }
    }
	
}

DailyDiary/Models/ErrorViewModel.cs
namespace DailyDiary.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

DailyDiary/Controllers/DiaryController.cs
using DailyDiary.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DailyDiary.Data;
namespace DailyDiary.Controllers
{

	public class DiaryController : Controller
	{
        private readonly DiaryContext _context;

        public DiaryController(DiaryContext context)
        {
            _context = context;
        }

        [HttpGet("/diary")]
        public IActionResult Index()
		{
			return View();
		}

		public IActionResult Create()
		{
			return View();
		}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  async Task<IActionResult> Create(Diary diary)
        {
            if (ModelState.IsValid)
            {
                await _context.Diary.AddAsync(diary);
                await _context.SaveChangesAsync();
                return View("Index");
            }
            return View(diary); // Return the view with the current model if validation fails
        }

        [HttpGet("/diary/Lists")]
        public async Task<IActionResult> ListAsync()
        {
            List<Diary> diaries = await _context.Diary.ToListAsync();
            return View(diaries);
        }

        public ActionResult Delete(int id)
        {
            var item = _context.Diary.Find(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var item = _context.Diary.Find(id);
            if (item == null)
            {
                return NotFound();
            }

            _context.Diary.Remove(item);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            var item = _context.Diary.Find(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditConfirmed(Diary diary)
        {
            var id = diary.SrNo;
            var item =  _context.Diary.Find(id);
            if (item == null)
            {
                return NotFound();
            }

            _context.Diary.Remove(item);
            await _context.Diary.AddAsync(diary);
            await _context.SaveChangesAsync();
            return RedirectToAction("List");
        }

        public ActionResult Details(int id)
        {
            var item = _context.Diary.Find(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }
    }
}

DailyDiary/Controllers/HomeController.cs
using DailyDiary.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DailyDiary.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

DailyDiary/Views/Diary/Create.cshtml
@model DailyDiary.Models.Diary

@{
    ViewData["Title"] = "Create";
}

<h1>View</h1>

<h4>Diary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SrNo" class="control-label"></label>
                <input asp-for="SrNo" class="form-control" />
                <span asp-validation-for="SrNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diary_Content" class="control-label"></label>
                <input asp-for="Diary_Content" class="form-control" />
                <span asp-validation-for="Diary_Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diary_Entry_Date" class="control-label"></label>
                <input asp-for="Diary_Entry_Date" class="form-control" />
                <span asp-validation-for="Diary_Entry_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DailyDiary/Views/Diary/Delete.cshtml
@model DailyDiary.Models.Diary

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Diary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diary_Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diary_Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diary_Entry_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diary_Entry_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SrNo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="List">Back to List</a>
    </form>
</div>

DailyDiary/Views/Diary/Details.cshtml
@model DailyDiary.Models.Diary

@{
    ViewData["Title"] = "Details";
}

<h1>View</h1>

<div>
    <h4>Diary</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diary_Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diary_Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Diary_Entry_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Diary_Entry_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.SrNo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DailyDiary/Views/Diary/Edit.cshtml
@model DailyDiary.Models.Diary

@{
    ViewData["Title"] = "Edit";
}

<h1>View</h1>

<h4>Diary</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SrNo" />
            <div class="form-group">
                <label asp-for="Diary_Content" class="control-label"></label>
                <input asp-for="Diary_Content" class="form-control" />
                <span asp-validation-for="Diary_Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diary_Entry_Date" class="control-label"></label>
                <input asp-for="Diary_Entry_Date" class="form-control" />
                <span asp-validation-for="Diary_Entry_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

DailyDiary/Views/Diary/Index.cshtml
@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

DailyDiary/Views/Diary/List.cshtml
@model IEnumerable<DailyDiary.Models.Diary>

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Diary_Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Diary_Entry_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Diary_Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diary_Entry_Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SrNo">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.SrNo">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.SrNo">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

DailyDiary/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    
</div>

DailyDiary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DailyDiary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DailyDiary.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DailyDiary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Diary" asp-action="Create">Add Entry</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Diary"
                                asp-action="List">Diary</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DailyDiary
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>